import os

os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --seq_num 1')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --seq_num 2')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --seq_num 3')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --seq_num 4')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --seq_num 5')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --seq_num 6')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --seq_num 7')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --seq_num 8')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --seq_num 9')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --seq_num 10')

os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 1')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 2')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 3')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 2.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 4')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 5')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 6')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 7')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 8')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 9')
os.system('python lj_rss_1.py --wandb --natoms 40 --scale 3.0 --total_trajectories 2000 --minsep 1.0 --random_start --seq_num 10')